### ISSUE TITLE
CI configuration is deploying every commit on master

### ISSUE THREAD

**Issue by ftm** [ftm/pyeactivities#10]
CircleCI appears to be making a new release on every commit to master, instead of only tagged commits.

According to [this discussion](https://discuss.circleci.com/t/how-to-deploy-only-on-tagged-and-master-commits/25581) the filters in the config are combined using OR. So where our config says:

```yaml
      - build-dist:
          requires:
            - test
          filters:
            tags:
              only: /\d+\.\d+\.\d+(?:-.*)?/
            branches:
              only: master
      - release-github:
          requires:
            - build-dist
          filters:
            tags:
              only: /\d+\.\d+\.\d+(?:-.*)?/
            branches:
              only: master
```

It matches the branch filter before the tag filter and runs the job.

According to the [CircleCI config docs](https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag), the config should be something like

```yaml
version: 2.1
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build:
          filters:  # required since `test` has tag filters AND requires `build`
            tags:
              only: /^config-test.*/
      - test:
          requires:
            - build
          filters:  # required since `deploy` has tag filters AND requires `test`
            tags:
              only: /^config-test.*/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^config-test.*/
            branches:
              ignore: /.*/

```
